require("globals")

return {
    [1] = {
        [1] = {
            {
                name = "term",
                index = 1,
                column_count = 1,
                gap_single_client = true,
                key = "t",
                layout = LAYOUT_BOTTOM,
                master_fill_policy = "expand",
                master_width_factor = 0.75,
                selected = true,
            },
            {
                name = "dev",
                index = 2,
                key = "d",
                layout = LAYOUT_BOTTOM,
                master_width_factor = 0.5,
            },
            {
                name = "surf",
                index = 3,
                key = "s",
                layout = LAYOUT_BOTTOM,
                master_width_factor = 0.5,
            },
            {
                name = "exec",
                index = 4,
                key = "x",
                layout = LAYOUT_MAX,
                master_width_factor = 0.5,
            },
            {
                name = "back",
                index = 5,
                key = "b",
                layout = LAYOUT_TILE,
                master_width_factor = 0.5,
            },
            {
                name = "coms",
                index = 6,
                key = "c",
                layout = LAYOUT_TILE,
                master_width_factor = 0.5,
            },
            {
                name = "wiki",
                index = 7,
                key = "w",
                layout = LAYOUT_MAX,
                master_width_factor = 0.5,
            },
            {
                name = "virt",
                index = 8,
                key = "v",
                layout = LAYOUT_TILE,
                master_width_factor = 0.5,
            },
            {
                name = "fnd",
                index = 9,
                key = "f",
                layout = LAYOUT_TILE,
                master_width_factor = 0.5,
            },
            {
                name = "apps",
                index = 10,
                key = "a",
                layout = LAYOUT_TILE,
                master_width_factor = 0.66,
                gap = 0,
                selected = true
            },
            {
                name = "run",
                index = 11,
                key = "r",
                layout = LAYOUT_BOTTOM,
                master_width_factor = 0.5,
                master_count = 1,
                gap = 0,
            },
            {
                name = "pres",
                index = 12,
                key = "p",
                layout = LAYOUT_FULL,
                master_width_factor = 0.5,
                gap = 0,
            },
            {
                name = "git",
                index = 13,
                key = "g",
                layout = LAYOUT_TILE,
                master_width_factor = 0.5,
            },
        }
    },
    [2] = {
        [1] = {
            {
                name = "term",
                index = 1,
                column_count = 1,
                gap_single_client = true,
                key = "t",
                layout = LAYOUT_BOTTOM,
                master_fill_policy = "expand",
                master_width_factor = 0.75,
                selected = true,
            },
            {
                name = "dev",
                index = 2,
                key = "d",
                layout = LAYOUT_BOTTOM,
                master_width_factor = 0.5,
            },
            {
                name = "surf",
                index = 3,
                key = "s",
                layout = LAYOUT_BOTTOM,
                master_width_factor = 0.5,
            },
            {
                name = "exec",
                index = 4,
                key = "x",
                layout = LAYOUT_MAX,
                master_width_factor = 0.5,
            },
            {
                name = "back",
                index = 5,
                key = "b",
                layout = LAYOUT_TILE,
                master_width_factor = 0.5,
            },
            {
                name = "coms",
                index = 6,
                key = "c",
                layout = LAYOUT_TILE,
                master_width_factor = 0.5,
            },
            {
                name = "wiki",
                index = 7,
                key = "w",
                layout = LAYOUT_MAX,
                master_width_factor = 0.5,
            },
            {
                name = "virt",
                index = 8,
                key = "v",
                layout = LAYOUT_TILE,
                master_width_factor = 0.5,
            },
            {
                name = "fnd",
                index = 9,
                key = "f",
                layout = LAYOUT_TILE,
                master_width_factor = 0.5,
            }
        },
        [2] = {
            {
                name = "apps",
                index = 1,
                key = "a",
                layout = LAYOUT_TILE,
                master_width_factor = 0.66,
                gap = 0,
                selected = true
            },
            {
                name = "run",
                index = 2,
                key = "r",
                layout = LAYOUT_BOTTOM,
                master_width_factor = 0.5,
                master_count = 1,
                gap = 0,
            },
            {
                name = "pres",
                index = 3,
                key = "p",
                layout = LAYOUT_FULL,
                master_width_factor = 0.5,
                gap = 0,
            },
            {
                name = "git",
                index = 4,
                key = "g",
                layout = LAYOUT_TILE,
                master_width_factor = 0.5,
            },
        }
    }
}
