require("globals")

return {
    {
        name = "term",
        screen = { 1, 1, 1 },
        index = { 1, 1, 1 },
        column_count = 1,
        gap_single_client = true,
        key = "t",
        layout = LAYOUT_BOTTOM,
        master_fill_policy = "expand",
        master_width_factor = 0.75,
        selected = true,
    },
    {
        name = "dev",
        screen = { 1, 1, 1 },
        index = { 2, 2, 2 },
        key = "d",
        layout = LAYOUT_BOTTOM,
        master_width_factor = 0.5,
    },
    {
        name = "surf",
        screen = { 1, 1, 1 },
        index = { 3, 3, 3 },
        key = "s",
        layout = LAYOUT_BOTTOM,
        master_width_factor = 0.5,
    },
    {
        name = "exec",
        screen = { 1, 1, 1 },
        index = { 4, 4, 4 },
        key = "x",
        layout = LAYOUT_MAX,
        master_width_factor = 0.5,
    },
    {
        name = "back",
        screen = { 1, 1, 1 },
        index = { 5, 5, 5 },
        key = "b",
        layout = LAYOUT_TILE,
        master_width_factor = 0.5,
    },
    {
        name = "comm",
        screen = { 1, 1, 1 },
        index = { 6, 6, 6 },
        key = "c",
        layout = LAYOUT_TILE,
        master_width_factor = 0.5,
    },
    {
        name = "wiki",
        screen = { 1, 1, 1 },
        index = { 7, 7, 7 },
        key = "w",
        layout = LAYOUT_MAX,
        master_width_factor = 0.5,
    },
    {
        name = "virt",
        screen = { 1, 1, 1 },
        index = { 8, 8, 8 },
        key = "v",
        layout = LAYOUT_TILE,
        master_width_factor = 0.5,
    },
    {
        name = "apps",
        screen = { 1, 2, 3 },
        index = { 9, 1, 1 },
        key = "a",
        layout = LAYOUT_TILE,
        master_width_factor = 0.66,
        gap = 0,
        selected = true
    },
    {
        name = "run",
        screen = { 1, 2, 2 },
        index = { 10, 2, 1 },
        key = "r",
        layout = LAYOUT_TILE,
        master_width_factor = 0.5,
        master_count = 3,
        gap = 0,
    },
    {
        name = "pres",
        screen = { 1, 2, 2 },
        index = { 11, 3, 2 },
        key = "p",
        layout = LAYOUT_FULL,
        master_width_factor = 0.5,
        gap = 0,
    },
    {
        name = "git",
        screen = { 1, 2, 2 },
        index = { 12, 4, 3 },
        key = "g",
        layout = LAYOUT_TILE,
        master_width_factor = 0.5,
    },
}
