require("globals")

return {
    {
        name = "term",
        index = 1,
        column_count = 1,
        gap_single_client = true,
        key = "t",
        layout = LAYOUT_BOTTOM,
        master_fill_policy = "expand",
        master_width_factor = 0.75,
        screen = 1,
        selected = true,
    },
    {
        name = "dev",
        index = 2,
        key = "d",
        layout = LAYOUT_BOTTOM,
        screen = 1,
        master_width_factor = 0.5,
    },
    {
        index = 3,
        name = "surf",
        key = "s",
        layout = LAYOUT_BOTTOM,
        screen = 1,
        master_width_factor = 0.5,
    },
    {
        index = 4,
        name = "exec",
        key = "x",
        layout = LAYOUT_MAX,
        screen = 1,
        master_width_factor = 0.5,
    },
    {
        index = 5,
        name = "back",
        key = "b",
        layout = LAYOUT_TILE,
        screen = 1,
        master_width_factor = 0.5,
    },
    {
        index = 6,
        name = "chat",
        key = "c",
        layout = LAYOUT_TILE,
        screen = 1,
        master_width_factor = 0.5,
    },
    {
        index = 7,
        name = "wiki",
        key = "w",
        layout = LAYOUT_MAX,
        screen = 1,
        master_width_factor = 0.5,
    },
    {
        index = 8,
        name = "virt",
        key = "v",
        layout = LAYOUT_TILE,
        screen = 1,
        master_width_factor = 0.5,
    },
    {
        index = 1,
        name = "apps",
        key = "a",
        layout = LAYOUT_TILE,
        screen = 2,
        master_width_factor = 0.66,
        gap = 0,
        selected = true
    },
    {
        index = 2,
        name = "run",
        key = "r",
        layout = LAYOUT_TILE,
        screen = 2,
        master_width_factor = 0.5,
        master_count = 3,
        gap = 0,
    },
    {
        index = 3,
        name = "pres",
        key = "p",
        layout = LAYOUT_FULL,
        screen = 2,
        master_width_factor = 0.5,
        gap = 0,
    },
    {
        index = 4,
        name = "git",
        key = "g",
        layout = LAYOUT_TILE,
        screen = 2,
        master_width_factor = 0.5,
    },
}
