apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pgadmin
  name: pgadmin
spec:
  containers:
    - name: pgadmin
      image: dpage/pgadmin4:latest
      volumeMounts:
        - mountPath: /var/lib/pgadmin
          name: pgadmin-data
        - mountPath: /pgadmin4/servers.json
          subPath: servers.json
          name: pgadmin-servers
      ports:
        - containerPort: 80
          hostPort: 5050
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: pgadmin@example.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: K4HeAk1xzNg4OZ9zAZVKSSwXs
        - name: TZ
          value: Asia/Taipei
  restartPolicy: OnFailure
  volumes:
    - name: pgadmin-data
      persistentVolumeClaim:
        claimName: pgadmin-data
