require('mappings')
require('settings')
require('colors')

require('config-packer')
require('config-nvim-tree')
require('config-lsp.language-servers')
require('config-lsp.nvim-cmp')
require('config-lualine')
require('config-telescope')
require('config-barbar')
