#!/usr/bin/env sh

if git grep --cached -qE -e "f(it|describe|context) ['\"]" -e "Pry::ColorPrinter\.pp\(\w)"; then
    echo 'Commit contains focused tests or puts statements.'
    exit 1
fi

# Run ESLint on staged .js files
for file in $(git diff --cached --name-only --diff-filter=ACM | grep ".rb$"); do
  if ! rubocop "$file" > /dev/null; then
    echo "Rubocop failed on staged file '$file'. Please fix the errors and try again."
    exit 1
  fi
done
