#!/bin/sh

alias setup_neovim="tplay playbooks/dev/neovim.yml"
alias setup_dotfiles="tailnet_setup_dotfiles"
alias sync_repos="tplay playbooks/workstation/sync_repos.yml"
alias syu="tplay playbooks/dev/update.yml"
alias tplay="cd ~/tailnet && ansible-playbook"
alias update_roles="cd ~/tailnet; ansible-galaxy install -r requirements.yml -f"

tailnet_setup_dotfiles () {
    cmd=ansible-playbook

    cd /home/pl/tailnet && $cmd playbooks/workstation/dotfiles.yml --limit $(hostname -d)
    cd /home/pl/devbox && $cmd playbooks/dev.yml -t dotfiles
}
