#!/bin/sh

source ~/.aliases.d/ansible
source ~/.aliases.d/dev
source ~/.aliases.d/exa
source ~/.aliases.d/git
source ~/.aliases.d/molecule
source ~/.aliases.d/pacman
source ~/.aliases.d/pass
source ~/.aliases.d/podman
source ~/.aliases.d/ranger
source ~/.aliases.d/ssh
source ~/.aliases.d/tailnet
source ~/.aliases.d/vagrant

alias cat="bat -p"
alias cdc="pwd | ctc"
alias chx="chmod +x"
alias ctc="cat_to_clipboard"
alias gud="gu ~/dotfiles"
alias gut="gu ~/tailnet"
alias pc="pass -c"
alias sal="source ~/.aliases"  
alias v="nvim_fg"
alias xo="xdg-open"

gu() {
  if [ -z "$1" ]; then
    gitui
  else
    gitui -d $1
  fi
}

run_molecule () {
  if ! type "molecule" > /dev/null; then
    source ~/code/venv/ansible/bin/activate
  fi
  export SCNR=${scenario:='default'}
  molecule "$@"
}

nvim_fg () {
    if [ -z "$(jobs | grep nvim)" ]; then
        nvim $@
    else
        fg
    fi
}

cat_to_clipboard () {
    bat -p $1 | xclip -selection clipboard
}

wiki () {
    cd ~/Notes && nvim +"lua require('kiwi').open_wiki_index()" index.md
}
