export ZSH=~/.oh-my-zsh

export LC_ALL="en_US.UTF-8"

export EDITOR=nvim

export PATH=":/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games/:$HOME/.npm-global/bin/:$HOME/.local/bin/:$HOME/.cargo/bin"

export LD_LIBRARY_PATH=/usr/local/lib

export SHELL=/bin/zsh

export PAGER="most"

export REDMI_BUDS4="E0:08:71:88:2A:B9"
export H15_PRO="41:42:5B:66:E5:77"
