# path to your oh-my-zsh installation.
# disable CTRL-s flow control
stty -ixon

ZSH_THEME="avit"

autoload -Uz compinit
compinit

plugins=(zsh-syntax-highlighting zsh-autosuggestions git pass fasd podman kubectl systemd)

if [[ -z $SSH_CONNECTION ]]; then
    plugins+=(notify)
fi

source $ZSH/oh-my-zsh.sh

eval "$(fasd --init auto)"

source ~/.aliases

# zsh-notify
zstyle ':notify:*' error-title "Command failed (in #{time_elapsed})"
zstyle ':notify:*' success-title "Command finished (in #{time_elapsed})"
zstyle ':notify:*' success-icon "/home/pl/dotfiles/arch/img/notify_icon_success.png"
zstyle ':notify:*' error-icon "/home/pl/dotfiles/arch/img/notify_icon_error.png"
zstyle ':notify:*' command-complete-timeout 3
# zstyle ':notify:*' expire-time 30000
zstyle ':notify:*' app-name sh
zstyle ':notify:*' activate-terminal no
zstyle ':notify:*' enable-on-ssh no

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/pl/google-cloud-sdk/path.zsh.inc' ]; then . '/home/pl/google-cloud-sdk/path.zsh.inc'; fi
