# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

unset rc

source ~/.bashenv

if [[ -z $SSH_CONNECTION ]]; then
  export GPG_TTY="$(tty)"
  export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
  gpgconf --launch gpg-agent
fi

# aliases
ansp () {
  if ! type "ansible-playbook" > /dev/null; then
    source ~/.venv/ansible/bin/activate
  fi
  ansible-playbook "$@"
}

run_molecule () {
  if ! type "molecule" &> /dev/null; then
    source ~/.venv/ansible/bin/activate
  fi
  molecule "$@"
}

alias molc='run_molecule converge'
alias moll='run_molecule login'
alias mold='run_molecule destroy'
alias molv='run_molecule verify'
alias molrr="molr && molc"

alias m="minikube"
